Check dockerize

diff --git a/.github/workflows/build-mudlet.yml b/.github/workflows/build-mudlet.yml
--- a/.github/workflows/build-mudlet.yml
+++ b/.github/workflows/build-mudlet.yml
@@ -339,57 +339,57 @@ jobs:
         AC_USERNAME: ${{secrets.APPLE_USERNAME}}
         AC_PASSWORD: ${{secrets.APPLE_PASSWORD}}
 
-    - name: Upload packaged Mudlet
-      uses: actions/upload-artifact@v3
-      if: env.UPLOAD_FILENAME
-      with:
-        name: ${{env.UPLOAD_FILENAME}}
-        path: ${{env.FOLDER_TO_UPLOAD}}
+    # - name: Upload packaged Mudlet
+    #   uses: actions/upload-artifact@v3
+    #   if: env.UPLOAD_FILENAME
+    #   with:
+    #     name: ${{env.UPLOAD_FILENAME}}
+    #     path: ${{env.FOLDER_TO_UPLOAD}}
 
-    - name: Submit to make.mudlet.org
-      if: env.UPLOAD_FILENAME
-      run: curl -X POST "https://make.mudlet.org/snapshots/gha_queue.php?artifact_name=${{env.UPLOAD_FILENAME}}&unzip=1"
-      shell: bash
+    # - name: Submit to make.mudlet.org
+    #   if: env.UPLOAD_FILENAME
+    #   run: curl -X POST "https://make.mudlet.org/snapshots/gha_queue.php?artifact_name=${{env.UPLOAD_FILENAME}}&unzip=1"
+    #   shell: bash
 
-    # we need to be in the right place for LuaGlobals.lua to load
-    - name: Prep binary for running tests
-      if: matrix.run_tests == 'true'
-      run: cp ${{runner.workspace}}/b/ninja/src/mudlet ${{github.workspace}}/src
-      shell: bash
+    # # we need to be in the right place for LuaGlobals.lua to load
+    # - name: Prep binary for running tests
+    #   if: matrix.run_tests == 'true'
+    #   run: cp ${{runner.workspace}}/b/ninja/src/mudlet ${{github.workspace}}/src
+    #   shell: bash
 
-    - name: Run Lua tests
-      if: matrix.run_tests == 'true'
-      timeout-minutes: 5
-      uses: GabrielBB/xvfb-action@v1.6
-      with:
-        run: ${{github.workspace}}/src/mudlet --profile "Mudlet self-test" --mirror
-      env:
-        AUTORUN_BUSTED_TESTS: 'true'
-        TESTS_DIRECTORY: ${{github.workspace}}/src/mudlet-lua/tests
-        QUIT_MUDLET_AFTER_TESTS: 'true'
+    # - name: Run Lua tests
+    #   if: matrix.run_tests == 'true'
+    #   timeout-minutes: 5
+    #   uses: GabrielBB/xvfb-action@v1.6
+    #   with:
+    #     run: ${{github.workspace}}/src/mudlet --profile "Mudlet self-test" --mirror
+    #   env:
+    #     AUTORUN_BUSTED_TESTS: 'true'
+    #     TESTS_DIRECTORY: ${{github.workspace}}/src/mudlet-lua/tests
+    #     QUIT_MUDLET_AFTER_TESTS: 'true'
 
-    - name: Passed Lua tests
-      if: matrix.run_tests == 'true'
-      run: |
-        if [ -e /tmp/busted-tests-failed ]
-        then
-          echo "Lua tests failed - see the action above for detailed output."
-          exit 1
-        fi
+    # - name: Passed Lua tests
+    #   if: matrix.run_tests == 'true'
+    #   run: |
+    #     if [ -e /tmp/busted-tests-failed ]
+    #     then
+    #       echo "Lua tests failed - see the action above for detailed output."
+    #       exit 1
+    #     fi
 
-    - name: (windows) Show relevant setup logs
-      if: failure() && runner.os == 'Windows'
-      run: |
-        $env:WORKING_BASE_DIR = "${{runner.workspace}}\src"
-        if (Test-Path -Path "$env:WORKING_BASE_DIR\stderr.log") {
-          echo "Standard error log from non-vcpkg dependencies: "
-          cat $env:WORKING_BASE_DIR\stderr.log
-        }
-        if (Test-Path -Path "$env:WORKING_BASE_DIR\stdout.log") {
-          echo "Standard output log from non-vcpkg dependencies: "
-          cat $env:WORKING_BASE_DIR\stdout.log
-        }
-        if (Test-Path -Path "${{runner.workspace}}/b/ninja/CMakeFiles/CMakeOutput.log") {
-          echo "CMakeOutput.log: "
-          cat "${{runner.workspace}}/b/ninja/CMakeFiles/CMakeOutput.log"
-        }
+    # - name: (windows) Show relevant setup logs
+    #   if: failure() && runner.os == 'Windows'
+    #   run: |
+    #     $env:WORKING_BASE_DIR = "${{runner.workspace}}\src"
+    #     if (Test-Path -Path "$env:WORKING_BASE_DIR\stderr.log") {
+    #       echo "Standard error log from non-vcpkg dependencies: "
+    #       cat $env:WORKING_BASE_DIR\stderr.log
+    #     }
+    #     if (Test-Path -Path "$env:WORKING_BASE_DIR\stdout.log") {
+    #       echo "Standard output log from non-vcpkg dependencies: "
+    #       cat $env:WORKING_BASE_DIR\stdout.log
+    #     }
+    #     if (Test-Path -Path "${{runner.workspace}}/b/ninja/CMakeFiles/CMakeOutput.log") {
+    #       echo "CMakeOutput.log: "
+    #       cat "${{runner.workspace}}/b/ninja/CMakeFiles/CMakeOutput.log"
+    #     }
